name: Release

on:
  push:
    tags:
      - '*'

jobs:
  test:
    uses: ./.github/workflows/test.yml
  docker:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ github.repository }}
      - uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: startsWith(github.ref, 'refs/tags/')
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}