name: Release

on:
  push:
    tags:
      - '*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  docker:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # Build and push the image to GitHub Packages Container registry
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        id: build-and-push
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      # Sign the image
      - uses: sigstore/cosign-installer@v3
      - run: cosign version
      - run: cosign sign --yes --rekor-url "https://rekor.sigstore.dev/" "ghcr.io/${{ env.REPO }}@${{ env.DIGEST }}"
        env:
          REPO: ${{ github.repository }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
