name: Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref }}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: 'npm'
      - run: corepack enable
      - run: corepack install
      - run: node -v
      - run: corepack npm -v
      - run: corepack npm ci
      - run: corepack npm test
